
	 
	/*
	 *	This content is generated from the API File Info.
	 *	(Alt+Shift+Ctrl+I).
	 *
	 *	@desc 		
	 *	@file 		travel_2
	 *	@date 		Friday 29th of July 2022 10:26:31 AM
	 *	@title 		Page 1
	 *	@author 	
	 *	@keywords 	
	 *	@generator 	Export Kit v1.3.figma
	 *
	 */
	

package exportkit.figma;

import android.app.Activity;
import android.os.Bundle;


import android.view.View;
import android.widget.TextView;
import android.widget.ImageView;

public class travel_2_activity extends Activity {

	
	private View _bg__travel_2_ek2;
	private TextView title;
	private View ink;
	private TextView title_ek1;
	private View box_shadow;
	private TextView _ang_ch_y;
	private TextView _ang_ch_;
	private TextView _____ng;
	private TextView _206;
	private TextView _2022;
	private ImageView vector;
	private ImageView vector_ek1;
	private TextView th_ng_6;
	private ImageView vector_ek2;
	private ImageView vector_ek3;
	private TextView day;
	private TextView day_ek1;
	private TextView day_ek2;
	private TextView day_ek3;
	private TextView day_ek4;
	private TextView day_ek5;
	private TextView day_ek6;
	private TextView day_ek8;
	private View dot;
	private View dot_ek1;
	private View dot_ek2;
	private TextView day_ek10;
	private TextView day_ek12;
	private View dot_ek4;
	private TextView day_ek14;
	private View dot_ek5;
	private TextView day_ek16;
	private TextView day_ek18;
	private TextView day_ek20;
	private View dot_ek7;
	private View dot_ek8;
	private View dot_ek9;
	private TextView day_ek22;
	private View dot_ek10;
	private View dot_ek11;
	private View dot_ek12;
	private TextView day_ek24;
	private View dot_ek13;
	private View dot_ek14;
	private View dot_ek15;
	private TextView day_ek26;
	private View dot_ek16;
	private View dot_ek17;
	private View dot_ek18;
	private TextView day_ek28;
	private View dot_ek19;
	private View dot_ek20;
	private View dot_ek21;
	private TextView day_ek30;
	private View dot_ek22;
	private View dot_ek23;
	private View dot_ek24;
	private TextView day_ek32;
	private View dot_ek25;
	private View dot_ek26;
	private View dot_ek27;
	private TextView day_ek34;
	private View dot_ek28;
	private View dot_ek29;
	private View dot_ek30;
	private TextView day_ek36;
	private View dot_ek31;
	private View dot_ek32;
	private View dot_ek33;
	private TextView day_ek38;
	private View dot_ek34;
	private View dot_ek35;
	private View dot_ek36;
	private TextView day_ek40;
	private View dot_ek37;
	private View dot_ek38;
	private View dot_ek39;
	private TextView day_ek42;
	private View dot_ek40;
	private View dot_ek41;
	private View dot_ek42;
	private TextView day_ek44;
	private View dot_ek43;
	private View dot_ek44;
	private View dot_ek45;
	private TextView day_ek46;
	private View dot_ek46;
	private View dot_ek47;
	private View dot_ek48;
	private TextView day_ek48;
	private View dot_ek49;
	private View dot_ek50;
	private View dot_ek51;
	private TextView day_ek50;
	private View dot_ek52;
	private View dot_ek53;
	private View dot_ek54;
	private TextView day_ek52;
	private View dot_ek55;
	private View dot_ek56;
	private View dot_ek57;
	private TextView day_ek54;
	private View dot_ek58;
	private View dot_ek59;
	private View dot_ek60;
	private TextView day_ek56;
	private View dot_ek61;
	private View dot_ek62;
	private View dot_ek63;
	private TextView day_ek58;
	private View dot_ek65;
	private TextView day_ek60;
	private View dot_ek67;
	private View dot_ek68;
	private View dot_ek69;
	private TextView day_ek62;
	private View dot_ek70;
	private TextView day_ek64;
	private View dot_ek73;
	private TextView day_ek66;
	private View dot_ek76;
	private View dot_ek78;
	private TextView day_ek68;
	private View dot_ek80;
	private TextView day_ek70;
	private View dot_ek82;
	private View dot_ek83;
	private View dot_ek84;
	private TextView day_ek72;
	private View dot_ek85;
	private View dot_ek86;
	private View dot_ek87;
	private TextView day_ek74;
	private View dot_ek88;
	private View dot_ek89;
	private View dot_ek90;
	private TextView day_ek76;
	private View dot_ek91;
	private View dot_ek92;
	private View dot_ek93;
	private TextView day_ek78;
	private View dot_ek94;
	private View dot_ek95;
	private View dot_ek96;
	private TextView day_ek80;
	private View dot_ek97;
	private View dot_ek98;
	private View dot_ek99;
	private TextView day_ek82;
	private View dot_ek100;
	private View dot_ek101;
	private View dot_ek102;
	private TextView day_ek84;
	private View dot_ek103;
	private View dot_ek104;
	private View dot_ek105;
	private TextView day_ek86;
	private View dot_ek106;
	private View dot_ek107;
	private View dot_ek108;
	private TextView day_ek88;
	private View dot_ek109;
	private View dot_ek110;
	private View dot_ek111;
	private TextView day_ek90;
	private View dot_ek112;
	private View dot_ek113;
	private View dot_ek114;
	private ImageView vector_ek4;
	private TextView label;
	private ImageView vector_ek5;
	private TextView label_ek1;
	private ImageView vector_ek6;
	private TextView label_ek2;
	private View dot_ek115;
	private View dot_ek116;
	private View dot_ek117;
	private View dot_ek118;
	private View dot_ek119;
	private View dot_ek120;
	private View dot_ek121;
	private TextView title_ek4;
	private View ink_ek1;
	private TextView title_ek5;
	private View box_shadow_ek1;
	private TextView _ang_ch_y_ek1;
	private TextView _ang_ch__ek1;
	private TextView _____ng_ek1;
	private TextView _206_ek1;
	private TextView _2022_ek1;
	private ImageView vector_ek7;
	private ImageView vector_ek8;
	private TextView th_ng_6_ek1;
	private ImageView vector_ek9;
	private ImageView vector_ek10;
	private TextView day_ek91;
	private TextView day_ek92;
	private TextView day_ek93;
	private TextView day_ek94;
	private TextView day_ek95;
	private TextView day_ek96;
	private TextView day_ek97;
	private TextView day_ek99;
	private View dot_ek122;
	private View dot_ek123;
	private View dot_ek124;
	private TextView day_ek101;
	private TextView day_ek103;
	private View dot_ek126;
	private TextView day_ek105;
	private View dot_ek127;
	private TextView day_ek107;
	private TextView day_ek109;
	private TextView day_ek111;
	private View dot_ek129;
	private View dot_ek130;
	private View dot_ek131;
	private TextView day_ek113;
	private View dot_ek132;
	private View dot_ek133;
	private View dot_ek134;
	private TextView day_ek115;
	private View dot_ek135;
	private View dot_ek136;
	private View dot_ek137;
	private TextView day_ek117;
	private View dot_ek138;
	private View dot_ek139;
	private View dot_ek140;
	private TextView day_ek119;
	private View dot_ek141;
	private View dot_ek142;
	private View dot_ek143;
	private TextView day_ek121;
	private View dot_ek144;
	private View dot_ek145;
	private View dot_ek146;
	private TextView day_ek123;
	private View dot_ek147;
	private View dot_ek148;
	private View dot_ek149;
	private TextView day_ek125;
	private View dot_ek150;
	private View dot_ek151;
	private View dot_ek152;
	private TextView day_ek127;
	private View dot_ek153;
	private View dot_ek154;
	private View dot_ek155;
	private TextView day_ek129;
	private View dot_ek156;
	private View dot_ek157;
	private View dot_ek158;
	private TextView day_ek131;
	private View dot_ek159;
	private View dot_ek160;
	private View dot_ek161;
	private TextView day_ek133;
	private View dot_ek162;
	private View dot_ek163;
	private View dot_ek164;
	private TextView day_ek135;
	private View dot_ek165;
	private View dot_ek166;
	private View dot_ek167;
	private TextView day_ek137;
	private View dot_ek168;
	private View dot_ek169;
	private View dot_ek170;
	private TextView day_ek139;
	private View dot_ek171;
	private View dot_ek172;
	private View dot_ek173;
	private TextView day_ek141;
	private View dot_ek174;
	private View dot_ek175;
	private View dot_ek176;
	private TextView day_ek143;
	private View dot_ek177;
	private View dot_ek178;
	private View dot_ek179;
	private TextView day_ek145;
	private View dot_ek180;
	private View dot_ek181;
	private View dot_ek182;
	private TextView day_ek147;
	private View dot_ek183;
	private View dot_ek184;
	private View dot_ek185;
	private TextView day_ek149;
	private View dot_ek187;
	private TextView day_ek151;
	private View dot_ek189;
	private View dot_ek190;
	private View dot_ek191;
	private TextView day_ek153;
	private View dot_ek192;
	private TextView day_ek155;
	private View dot_ek195;
	private TextView day_ek157;
	private View dot_ek198;
	private View dot_ek200;
	private TextView day_ek159;
	private View dot_ek202;
	private TextView day_ek161;
	private View dot_ek204;
	private View dot_ek205;
	private View dot_ek206;
	private TextView day_ek163;
	private View dot_ek207;
	private View dot_ek208;
	private View dot_ek209;
	private TextView day_ek165;
	private View dot_ek210;
	private View dot_ek211;
	private View dot_ek212;
	private TextView day_ek167;
	private View dot_ek213;
	private View dot_ek214;
	private View dot_ek215;
	private TextView day_ek169;
	private View dot_ek216;
	private View dot_ek217;
	private View dot_ek218;
	private TextView day_ek171;
	private View dot_ek219;
	private View dot_ek220;
	private View dot_ek221;
	private TextView day_ek173;
	private View dot_ek222;
	private View dot_ek223;
	private View dot_ek224;
	private TextView day_ek175;
	private View dot_ek225;
	private View dot_ek226;
	private View dot_ek227;
	private TextView day_ek177;
	private View dot_ek228;
	private View dot_ek229;
	private View dot_ek230;
	private TextView day_ek179;
	private View dot_ek231;
	private View dot_ek232;
	private View dot_ek233;
	private TextView day_ek181;
	private View dot_ek234;
	private View dot_ek235;
	private View dot_ek236;
	private ImageView vector_ek11;
	private TextView label_ek3;
	private ImageView vector_ek12;
	private TextView label_ek4;
	private ImageView vector_ek13;
	private TextView label_ek5;
	private ImageView vector_ek14;
	private TextView label_ek6;
	private ImageView vector_ek15;
	private TextView label_ek7;
	private ImageView vector_ek16;
	private TextView label_ek8;
	private View dot_ek237;
	private View dot_ek238;
	private View dot_ek239;
	private View dot_ek240;
	private View dot_ek241;
	private View dot_ek242;
	private ImageView logo_png__1__2;
	private TextView title_ek8;
	private View ink_ek2;
	private TextView title_ek9;
	private View box_shadow_ek2;
	private TextView _ang_ch_y_ek2;
	private TextView _ang_ch__ek2;
	private TextView _____ng_ek2;
	private TextView _206_ek2;
	private TextView _2022_ek2;
	private ImageView vector_ek17;
	private ImageView vector_ek18;
	private TextView th_ng_6_ek2;
	private ImageView vector_ek19;
	private ImageView vector_ek20;
	private TextView day_ek182;
	private TextView day_ek183;
	private TextView day_ek184;
	private TextView day_ek185;
	private TextView day_ek186;
	private TextView day_ek187;
	private TextView day_ek188;
	private TextView day_ek190;
	private View dot_ek243;
	private View dot_ek244;
	private View dot_ek245;
	private TextView day_ek192;
	private TextView day_ek194;
	private View dot_ek247;
	private TextView day_ek196;
	private View dot_ek248;
	private TextView day_ek198;
	private TextView day_ek200;
	private TextView day_ek202;
	private View dot_ek250;
	private View dot_ek251;
	private View dot_ek252;
	private TextView day_ek204;
	private View dot_ek253;
	private View dot_ek254;
	private View dot_ek255;
	private TextView day_ek206;
	private View dot_ek256;
	private View dot_ek257;
	private View dot_ek258;
	private TextView day_ek208;
	private View dot_ek259;
	private View dot_ek260;
	private View dot_ek261;
	private TextView day_ek210;
	private View dot_ek262;
	private View dot_ek263;
	private View dot_ek264;
	private TextView day_ek212;
	private View dot_ek265;
	private View dot_ek266;
	private View dot_ek267;
	private TextView day_ek214;
	private View dot_ek268;
	private View dot_ek269;
	private View dot_ek270;
	private TextView day_ek216;
	private View dot_ek271;
	private View dot_ek272;
	private View dot_ek273;
	private TextView day_ek218;
	private View dot_ek274;
	private View dot_ek275;
	private View dot_ek276;
	private TextView day_ek220;
	private View dot_ek277;
	private View dot_ek278;
	private View dot_ek279;
	private TextView day_ek222;
	private View dot_ek280;
	private View dot_ek281;
	private View dot_ek282;
	private TextView day_ek224;
	private View dot_ek283;
	private View dot_ek284;
	private View dot_ek285;
	private TextView day_ek226;
	private View dot_ek286;
	private View dot_ek287;
	private View dot_ek288;
	private TextView day_ek228;
	private View dot_ek289;
	private View dot_ek290;
	private View dot_ek291;
	private TextView day_ek230;
	private View dot_ek292;
	private View dot_ek293;
	private View dot_ek294;
	private TextView day_ek232;
	private View dot_ek295;
	private View dot_ek296;
	private View dot_ek297;
	private TextView day_ek234;
	private View dot_ek298;
	private View dot_ek299;
	private View dot_ek300;
	private TextView day_ek236;
	private View dot_ek301;
	private View dot_ek302;
	private View dot_ek303;
	private TextView day_ek238;
	private View dot_ek304;
	private View dot_ek305;
	private View dot_ek306;
	private TextView day_ek240;
	private View dot_ek308;
	private TextView day_ek242;
	private View dot_ek310;
	private View dot_ek311;
	private View dot_ek312;
	private TextView day_ek244;
	private View dot_ek313;
	private TextView day_ek246;
	private View dot_ek316;
	private TextView day_ek248;
	private View dot_ek319;
	private View dot_ek321;
	private TextView day_ek250;
	private View dot_ek323;
	private TextView day_ek252;
	private View dot_ek325;
	private View dot_ek326;
	private View dot_ek327;
	private TextView day_ek254;
	private View dot_ek328;
	private View dot_ek329;
	private View dot_ek330;
	private TextView day_ek256;
	private View dot_ek331;
	private View dot_ek332;
	private View dot_ek333;
	private TextView day_ek258;
	private View dot_ek334;
	private View dot_ek335;
	private View dot_ek336;
	private TextView day_ek260;
	private View dot_ek337;
	private View dot_ek338;
	private View dot_ek339;
	private TextView day_ek262;
	private View dot_ek340;
	private View dot_ek341;
	private View dot_ek342;
	private TextView day_ek264;
	private View dot_ek343;
	private View dot_ek344;
	private View dot_ek345;
	private TextView day_ek266;
	private View dot_ek346;
	private View dot_ek347;
	private View dot_ek348;
	private TextView day_ek268;
	private View dot_ek349;
	private View dot_ek350;
	private View dot_ek351;
	private TextView day_ek270;
	private View dot_ek352;
	private View dot_ek353;
	private View dot_ek354;
	private TextView day_ek272;
	private View dot_ek355;
	private View dot_ek356;
	private View dot_ek357;
	private ImageView vector_ek21;
	private TextView label_ek9;
	private ImageView vector_ek22;
	private TextView label_ek10;
	private ImageView vector_ek23;
	private TextView label_ek11;
	private ImageView vector_ek24;
	private TextView active;
	private ImageView fill_1;
	private ImageView group_5;
	private TextView inactive;
	private ImageView fill_1_ek1;
	private ImageView fill_3;
	private ImageView fill_5;
	private ImageView group_9;
	private TextView inactive_ek1;
	private ImageView vector_ek25;
	private TextView inactive_ek2;
	private ImageView group_3;
	private ImageView group_6;
	private TextView inactive_ek3;
	private ImageView calendar_1;

	@Override
	public void onCreate(Bundle savedInstanceState) {

		super.onCreate(savedInstanceState);
		setContentView(R.layout.travel_2);

		
		_bg__travel_2_ek2 = (View) findViewById(R.id._bg__travel_2_ek2);
		title = (TextView) findViewById(R.id.title);
		ink = (View) findViewById(R.id.ink);
		title_ek1 = (TextView) findViewById(R.id.title_ek1);
		box_shadow = (View) findViewById(R.id.box_shadow);
		_ang_ch_y = (TextView) findViewById(R.id._ang_ch_y);
		_ang_ch_ = (TextView) findViewById(R.id._ang_ch_);
		_____ng = (TextView) findViewById(R.id._____ng);
		_206 = (TextView) findViewById(R.id._206);
		_2022 = (TextView) findViewById(R.id._2022);
		vector = (ImageView) findViewById(R.id.vector);
		vector_ek1 = (ImageView) findViewById(R.id.vector_ek1);
		th_ng_6 = (TextView) findViewById(R.id.th_ng_6);
		vector_ek2 = (ImageView) findViewById(R.id.vector_ek2);
		vector_ek3 = (ImageView) findViewById(R.id.vector_ek3);
		day = (TextView) findViewById(R.id.day);
		day_ek1 = (TextView) findViewById(R.id.day_ek1);
		day_ek2 = (TextView) findViewById(R.id.day_ek2);
		day_ek3 = (TextView) findViewById(R.id.day_ek3);
		day_ek4 = (TextView) findViewById(R.id.day_ek4);
		day_ek5 = (TextView) findViewById(R.id.day_ek5);
		day_ek6 = (TextView) findViewById(R.id.day_ek6);
		day_ek8 = (TextView) findViewById(R.id.day_ek8);
		dot = (View) findViewById(R.id.dot);
		dot_ek1 = (View) findViewById(R.id.dot_ek1);
		dot_ek2 = (View) findViewById(R.id.dot_ek2);
		day_ek10 = (TextView) findViewById(R.id.day_ek10);
		day_ek12 = (TextView) findViewById(R.id.day_ek12);
		dot_ek4 = (View) findViewById(R.id.dot_ek4);
		day_ek14 = (TextView) findViewById(R.id.day_ek14);
		dot_ek5 = (View) findViewById(R.id.dot_ek5);
		day_ek16 = (TextView) findViewById(R.id.day_ek16);
		day_ek18 = (TextView) findViewById(R.id.day_ek18);
		day_ek20 = (TextView) findViewById(R.id.day_ek20);
		dot_ek7 = (View) findViewById(R.id.dot_ek7);
		dot_ek8 = (View) findViewById(R.id.dot_ek8);
		dot_ek9 = (View) findViewById(R.id.dot_ek9);
		day_ek22 = (TextView) findViewById(R.id.day_ek22);
		dot_ek10 = (View) findViewById(R.id.dot_ek10);
		dot_ek11 = (View) findViewById(R.id.dot_ek11);
		dot_ek12 = (View) findViewById(R.id.dot_ek12);
		day_ek24 = (TextView) findViewById(R.id.day_ek24);
		dot_ek13 = (View) findViewById(R.id.dot_ek13);
		dot_ek14 = (View) findViewById(R.id.dot_ek14);
		dot_ek15 = (View) findViewById(R.id.dot_ek15);
		day_ek26 = (TextView) findViewById(R.id.day_ek26);
		dot_ek16 = (View) findViewById(R.id.dot_ek16);
		dot_ek17 = (View) findViewById(R.id.dot_ek17);
		dot_ek18 = (View) findViewById(R.id.dot_ek18);
		day_ek28 = (TextView) findViewById(R.id.day_ek28);
		dot_ek19 = (View) findViewById(R.id.dot_ek19);
		dot_ek20 = (View) findViewById(R.id.dot_ek20);
		dot_ek21 = (View) findViewById(R.id.dot_ek21);
		day_ek30 = (TextView) findViewById(R.id.day_ek30);
		dot_ek22 = (View) findViewById(R.id.dot_ek22);
		dot_ek23 = (View) findViewById(R.id.dot_ek23);
		dot_ek24 = (View) findViewById(R.id.dot_ek24);
		day_ek32 = (TextView) findViewById(R.id.day_ek32);
		dot_ek25 = (View) findViewById(R.id.dot_ek25);
		dot_ek26 = (View) findViewById(R.id.dot_ek26);
		dot_ek27 = (View) findViewById(R.id.dot_ek27);
		day_ek34 = (TextView) findViewById(R.id.day_ek34);
		dot_ek28 = (View) findViewById(R.id.dot_ek28);
		dot_ek29 = (View) findViewById(R.id.dot_ek29);
		dot_ek30 = (View) findViewById(R.id.dot_ek30);
		day_ek36 = (TextView) findViewById(R.id.day_ek36);
		dot_ek31 = (View) findViewById(R.id.dot_ek31);
		dot_ek32 = (View) findViewById(R.id.dot_ek32);
		dot_ek33 = (View) findViewById(R.id.dot_ek33);
		day_ek38 = (TextView) findViewById(R.id.day_ek38);
		dot_ek34 = (View) findViewById(R.id.dot_ek34);
		dot_ek35 = (View) findViewById(R.id.dot_ek35);
		dot_ek36 = (View) findViewById(R.id.dot_ek36);
		day_ek40 = (TextView) findViewById(R.id.day_ek40);
		dot_ek37 = (View) findViewById(R.id.dot_ek37);
		dot_ek38 = (View) findViewById(R.id.dot_ek38);
		dot_ek39 = (View) findViewById(R.id.dot_ek39);
		day_ek42 = (TextView) findViewById(R.id.day_ek42);
		dot_ek40 = (View) findViewById(R.id.dot_ek40);
		dot_ek41 = (View) findViewById(R.id.dot_ek41);
		dot_ek42 = (View) findViewById(R.id.dot_ek42);
		day_ek44 = (TextView) findViewById(R.id.day_ek44);
		dot_ek43 = (View) findViewById(R.id.dot_ek43);
		dot_ek44 = (View) findViewById(R.id.dot_ek44);
		dot_ek45 = (View) findViewById(R.id.dot_ek45);
		day_ek46 = (TextView) findViewById(R.id.day_ek46);
		dot_ek46 = (View) findViewById(R.id.dot_ek46);
		dot_ek47 = (View) findViewById(R.id.dot_ek47);
		dot_ek48 = (View) findViewById(R.id.dot_ek48);
		day_ek48 = (TextView) findViewById(R.id.day_ek48);
		dot_ek49 = (View) findViewById(R.id.dot_ek49);
		dot_ek50 = (View) findViewById(R.id.dot_ek50);
		dot_ek51 = (View) findViewById(R.id.dot_ek51);
		day_ek50 = (TextView) findViewById(R.id.day_ek50);
		dot_ek52 = (View) findViewById(R.id.dot_ek52);
		dot_ek53 = (View) findViewById(R.id.dot_ek53);
		dot_ek54 = (View) findViewById(R.id.dot_ek54);
		day_ek52 = (TextView) findViewById(R.id.day_ek52);
		dot_ek55 = (View) findViewById(R.id.dot_ek55);
		dot_ek56 = (View) findViewById(R.id.dot_ek56);
		dot_ek57 = (View) findViewById(R.id.dot_ek57);
		day_ek54 = (TextView) findViewById(R.id.day_ek54);
		dot_ek58 = (View) findViewById(R.id.dot_ek58);
		dot_ek59 = (View) findViewById(R.id.dot_ek59);
		dot_ek60 = (View) findViewById(R.id.dot_ek60);
		day_ek56 = (TextView) findViewById(R.id.day_ek56);
		dot_ek61 = (View) findViewById(R.id.dot_ek61);
		dot_ek62 = (View) findViewById(R.id.dot_ek62);
		dot_ek63 = (View) findViewById(R.id.dot_ek63);
		day_ek58 = (TextView) findViewById(R.id.day_ek58);
		dot_ek65 = (View) findViewById(R.id.dot_ek65);
		day_ek60 = (TextView) findViewById(R.id.day_ek60);
		dot_ek67 = (View) findViewById(R.id.dot_ek67);
		dot_ek68 = (View) findViewById(R.id.dot_ek68);
		dot_ek69 = (View) findViewById(R.id.dot_ek69);
		day_ek62 = (TextView) findViewById(R.id.day_ek62);
		dot_ek70 = (View) findViewById(R.id.dot_ek70);
		day_ek64 = (TextView) findViewById(R.id.day_ek64);
		dot_ek73 = (View) findViewById(R.id.dot_ek73);
		day_ek66 = (TextView) findViewById(R.id.day_ek66);
		dot_ek76 = (View) findViewById(R.id.dot_ek76);
		dot_ek78 = (View) findViewById(R.id.dot_ek78);
		day_ek68 = (TextView) findViewById(R.id.day_ek68);
		dot_ek80 = (View) findViewById(R.id.dot_ek80);
		day_ek70 = (TextView) findViewById(R.id.day_ek70);
		dot_ek82 = (View) findViewById(R.id.dot_ek82);
		dot_ek83 = (View) findViewById(R.id.dot_ek83);
		dot_ek84 = (View) findViewById(R.id.dot_ek84);
		day_ek72 = (TextView) findViewById(R.id.day_ek72);
		dot_ek85 = (View) findViewById(R.id.dot_ek85);
		dot_ek86 = (View) findViewById(R.id.dot_ek86);
		dot_ek87 = (View) findViewById(R.id.dot_ek87);
		day_ek74 = (TextView) findViewById(R.id.day_ek74);
		dot_ek88 = (View) findViewById(R.id.dot_ek88);
		dot_ek89 = (View) findViewById(R.id.dot_ek89);
		dot_ek90 = (View) findViewById(R.id.dot_ek90);
		day_ek76 = (TextView) findViewById(R.id.day_ek76);
		dot_ek91 = (View) findViewById(R.id.dot_ek91);
		dot_ek92 = (View) findViewById(R.id.dot_ek92);
		dot_ek93 = (View) findViewById(R.id.dot_ek93);
		day_ek78 = (TextView) findViewById(R.id.day_ek78);
		dot_ek94 = (View) findViewById(R.id.dot_ek94);
		dot_ek95 = (View) findViewById(R.id.dot_ek95);
		dot_ek96 = (View) findViewById(R.id.dot_ek96);
		day_ek80 = (TextView) findViewById(R.id.day_ek80);
		dot_ek97 = (View) findViewById(R.id.dot_ek97);
		dot_ek98 = (View) findViewById(R.id.dot_ek98);
		dot_ek99 = (View) findViewById(R.id.dot_ek99);
		day_ek82 = (TextView) findViewById(R.id.day_ek82);
		dot_ek100 = (View) findViewById(R.id.dot_ek100);
		dot_ek101 = (View) findViewById(R.id.dot_ek101);
		dot_ek102 = (View) findViewById(R.id.dot_ek102);
		day_ek84 = (TextView) findViewById(R.id.day_ek84);
		dot_ek103 = (View) findViewById(R.id.dot_ek103);
		dot_ek104 = (View) findViewById(R.id.dot_ek104);
		dot_ek105 = (View) findViewById(R.id.dot_ek105);
		day_ek86 = (TextView) findViewById(R.id.day_ek86);
		dot_ek106 = (View) findViewById(R.id.dot_ek106);
		dot_ek107 = (View) findViewById(R.id.dot_ek107);
		dot_ek108 = (View) findViewById(R.id.dot_ek108);
		day_ek88 = (TextView) findViewById(R.id.day_ek88);
		dot_ek109 = (View) findViewById(R.id.dot_ek109);
		dot_ek110 = (View) findViewById(R.id.dot_ek110);
		dot_ek111 = (View) findViewById(R.id.dot_ek111);
		day_ek90 = (TextView) findViewById(R.id.day_ek90);
		dot_ek112 = (View) findViewById(R.id.dot_ek112);
		dot_ek113 = (View) findViewById(R.id.dot_ek113);
		dot_ek114 = (View) findViewById(R.id.dot_ek114);
		vector_ek4 = (ImageView) findViewById(R.id.vector_ek4);
		label = (TextView) findViewById(R.id.label);
		vector_ek5 = (ImageView) findViewById(R.id.vector_ek5);
		label_ek1 = (TextView) findViewById(R.id.label_ek1);
		vector_ek6 = (ImageView) findViewById(R.id.vector_ek6);
		label_ek2 = (TextView) findViewById(R.id.label_ek2);
		dot_ek115 = (View) findViewById(R.id.dot_ek115);
		dot_ek116 = (View) findViewById(R.id.dot_ek116);
		dot_ek117 = (View) findViewById(R.id.dot_ek117);
		dot_ek118 = (View) findViewById(R.id.dot_ek118);
		dot_ek119 = (View) findViewById(R.id.dot_ek119);
		dot_ek120 = (View) findViewById(R.id.dot_ek120);
		dot_ek121 = (View) findViewById(R.id.dot_ek121);
		title_ek4 = (TextView) findViewById(R.id.title_ek4);
		ink_ek1 = (View) findViewById(R.id.ink_ek1);
		title_ek5 = (TextView) findViewById(R.id.title_ek5);
		box_shadow_ek1 = (View) findViewById(R.id.box_shadow_ek1);
		_ang_ch_y_ek1 = (TextView) findViewById(R.id._ang_ch_y_ek1);
		_ang_ch__ek1 = (TextView) findViewById(R.id._ang_ch__ek1);
		_____ng_ek1 = (TextView) findViewById(R.id._____ng_ek1);
		_206_ek1 = (TextView) findViewById(R.id._206_ek1);
		_2022_ek1 = (TextView) findViewById(R.id._2022_ek1);
		vector_ek7 = (ImageView) findViewById(R.id.vector_ek7);
		vector_ek8 = (ImageView) findViewById(R.id.vector_ek8);
		th_ng_6_ek1 = (TextView) findViewById(R.id.th_ng_6_ek1);
		vector_ek9 = (ImageView) findViewById(R.id.vector_ek9);
		vector_ek10 = (ImageView) findViewById(R.id.vector_ek10);
		day_ek91 = (TextView) findViewById(R.id.day_ek91);
		day_ek92 = (TextView) findViewById(R.id.day_ek92);
		day_ek93 = (TextView) findViewById(R.id.day_ek93);
		day_ek94 = (TextView) findViewById(R.id.day_ek94);
		day_ek95 = (TextView) findViewById(R.id.day_ek95);
		day_ek96 = (TextView) findViewById(R.id.day_ek96);
		day_ek97 = (TextView) findViewById(R.id.day_ek97);
		day_ek99 = (TextView) findViewById(R.id.day_ek99);
		dot_ek122 = (View) findViewById(R.id.dot_ek122);
		dot_ek123 = (View) findViewById(R.id.dot_ek123);
		dot_ek124 = (View) findViewById(R.id.dot_ek124);
		day_ek101 = (TextView) findViewById(R.id.day_ek101);
		day_ek103 = (TextView) findViewById(R.id.day_ek103);
		dot_ek126 = (View) findViewById(R.id.dot_ek126);
		day_ek105 = (TextView) findViewById(R.id.day_ek105);
		dot_ek127 = (View) findViewById(R.id.dot_ek127);
		day_ek107 = (TextView) findViewById(R.id.day_ek107);
		day_ek109 = (TextView) findViewById(R.id.day_ek109);
		day_ek111 = (TextView) findViewById(R.id.day_ek111);
		dot_ek129 = (View) findViewById(R.id.dot_ek129);
		dot_ek130 = (View) findViewById(R.id.dot_ek130);
		dot_ek131 = (View) findViewById(R.id.dot_ek131);
		day_ek113 = (TextView) findViewById(R.id.day_ek113);
		dot_ek132 = (View) findViewById(R.id.dot_ek132);
		dot_ek133 = (View) findViewById(R.id.dot_ek133);
		dot_ek134 = (View) findViewById(R.id.dot_ek134);
		day_ek115 = (TextView) findViewById(R.id.day_ek115);
		dot_ek135 = (View) findViewById(R.id.dot_ek135);
		dot_ek136 = (View) findViewById(R.id.dot_ek136);
		dot_ek137 = (View) findViewById(R.id.dot_ek137);
		day_ek117 = (TextView) findViewById(R.id.day_ek117);
		dot_ek138 = (View) findViewById(R.id.dot_ek138);
		dot_ek139 = (View) findViewById(R.id.dot_ek139);
		dot_ek140 = (View) findViewById(R.id.dot_ek140);
		day_ek119 = (TextView) findViewById(R.id.day_ek119);
		dot_ek141 = (View) findViewById(R.id.dot_ek141);
		dot_ek142 = (View) findViewById(R.id.dot_ek142);
		dot_ek143 = (View) findViewById(R.id.dot_ek143);
		day_ek121 = (TextView) findViewById(R.id.day_ek121);
		dot_ek144 = (View) findViewById(R.id.dot_ek144);
		dot_ek145 = (View) findViewById(R.id.dot_ek145);
		dot_ek146 = (View) findViewById(R.id.dot_ek146);
		day_ek123 = (TextView) findViewById(R.id.day_ek123);
		dot_ek147 = (View) findViewById(R.id.dot_ek147);
		dot_ek148 = (View) findViewById(R.id.dot_ek148);
		dot_ek149 = (View) findViewById(R.id.dot_ek149);
		day_ek125 = (TextView) findViewById(R.id.day_ek125);
		dot_ek150 = (View) findViewById(R.id.dot_ek150);
		dot_ek151 = (View) findViewById(R.id.dot_ek151);
		dot_ek152 = (View) findViewById(R.id.dot_ek152);
		day_ek127 = (TextView) findViewById(R.id.day_ek127);
		dot_ek153 = (View) findViewById(R.id.dot_ek153);
		dot_ek154 = (View) findViewById(R.id.dot_ek154);
		dot_ek155 = (View) findViewById(R.id.dot_ek155);
		day_ek129 = (TextView) findViewById(R.id.day_ek129);
		dot_ek156 = (View) findViewById(R.id.dot_ek156);
		dot_ek157 = (View) findViewById(R.id.dot_ek157);
		dot_ek158 = (View) findViewById(R.id.dot_ek158);
		day_ek131 = (TextView) findViewById(R.id.day_ek131);
		dot_ek159 = (View) findViewById(R.id.dot_ek159);
		dot_ek160 = (View) findViewById(R.id.dot_ek160);
		dot_ek161 = (View) findViewById(R.id.dot_ek161);
		day_ek133 = (TextView) findViewById(R.id.day_ek133);
		dot_ek162 = (View) findViewById(R.id.dot_ek162);
		dot_ek163 = (View) findViewById(R.id.dot_ek163);
		dot_ek164 = (View) findViewById(R.id.dot_ek164);
		day_ek135 = (TextView) findViewById(R.id.day_ek135);
		dot_ek165 = (View) findViewById(R.id.dot_ek165);
		dot_ek166 = (View) findViewById(R.id.dot_ek166);
		dot_ek167 = (View) findViewById(R.id.dot_ek167);
		day_ek137 = (TextView) findViewById(R.id.day_ek137);
		dot_ek168 = (View) findViewById(R.id.dot_ek168);
		dot_ek169 = (View) findViewById(R.id.dot_ek169);
		dot_ek170 = (View) findViewById(R.id.dot_ek170);
		day_ek139 = (TextView) findViewById(R.id.day_ek139);
		dot_ek171 = (View) findViewById(R.id.dot_ek171);
		dot_ek172 = (View) findViewById(R.id.dot_ek172);
		dot_ek173 = (View) findViewById(R.id.dot_ek173);
		day_ek141 = (TextView) findViewById(R.id.day_ek141);
		dot_ek174 = (View) findViewById(R.id.dot_ek174);
		dot_ek175 = (View) findViewById(R.id.dot_ek175);
		dot_ek176 = (View) findViewById(R.id.dot_ek176);
		day_ek143 = (TextView) findViewById(R.id.day_ek143);
		dot_ek177 = (View) findViewById(R.id.dot_ek177);
		dot_ek178 = (View) findViewById(R.id.dot_ek178);
		dot_ek179 = (View) findViewById(R.id.dot_ek179);
		day_ek145 = (TextView) findViewById(R.id.day_ek145);
		dot_ek180 = (View) findViewById(R.id.dot_ek180);
		dot_ek181 = (View) findViewById(R.id.dot_ek181);
		dot_ek182 = (View) findViewById(R.id.dot_ek182);
		day_ek147 = (TextView) findViewById(R.id.day_ek147);
		dot_ek183 = (View) findViewById(R.id.dot_ek183);
		dot_ek184 = (View) findViewById(R.id.dot_ek184);
		dot_ek185 = (View) findViewById(R.id.dot_ek185);
		day_ek149 = (TextView) findViewById(R.id.day_ek149);
		dot_ek187 = (View) findViewById(R.id.dot_ek187);
		day_ek151 = (TextView) findViewById(R.id.day_ek151);
		dot_ek189 = (View) findViewById(R.id.dot_ek189);
		dot_ek190 = (View) findViewById(R.id.dot_ek190);
		dot_ek191 = (View) findViewById(R.id.dot_ek191);
		day_ek153 = (TextView) findViewById(R.id.day_ek153);
		dot_ek192 = (View) findViewById(R.id.dot_ek192);
		day_ek155 = (TextView) findViewById(R.id.day_ek155);
		dot_ek195 = (View) findViewById(R.id.dot_ek195);
		day_ek157 = (TextView) findViewById(R.id.day_ek157);
		dot_ek198 = (View) findViewById(R.id.dot_ek198);
		dot_ek200 = (View) findViewById(R.id.dot_ek200);
		day_ek159 = (TextView) findViewById(R.id.day_ek159);
		dot_ek202 = (View) findViewById(R.id.dot_ek202);
		day_ek161 = (TextView) findViewById(R.id.day_ek161);
		dot_ek204 = (View) findViewById(R.id.dot_ek204);
		dot_ek205 = (View) findViewById(R.id.dot_ek205);
		dot_ek206 = (View) findViewById(R.id.dot_ek206);
		day_ek163 = (TextView) findViewById(R.id.day_ek163);
		dot_ek207 = (View) findViewById(R.id.dot_ek207);
		dot_ek208 = (View) findViewById(R.id.dot_ek208);
		dot_ek209 = (View) findViewById(R.id.dot_ek209);
		day_ek165 = (TextView) findViewById(R.id.day_ek165);
		dot_ek210 = (View) findViewById(R.id.dot_ek210);
		dot_ek211 = (View) findViewById(R.id.dot_ek211);
		dot_ek212 = (View) findViewById(R.id.dot_ek212);
		day_ek167 = (TextView) findViewById(R.id.day_ek167);
		dot_ek213 = (View) findViewById(R.id.dot_ek213);
		dot_ek214 = (View) findViewById(R.id.dot_ek214);
		dot_ek215 = (View) findViewById(R.id.dot_ek215);
		day_ek169 = (TextView) findViewById(R.id.day_ek169);
		dot_ek216 = (View) findViewById(R.id.dot_ek216);
		dot_ek217 = (View) findViewById(R.id.dot_ek217);
		dot_ek218 = (View) findViewById(R.id.dot_ek218);
		day_ek171 = (TextView) findViewById(R.id.day_ek171);
		dot_ek219 = (View) findViewById(R.id.dot_ek219);
		dot_ek220 = (View) findViewById(R.id.dot_ek220);
		dot_ek221 = (View) findViewById(R.id.dot_ek221);
		day_ek173 = (TextView) findViewById(R.id.day_ek173);
		dot_ek222 = (View) findViewById(R.id.dot_ek222);
		dot_ek223 = (View) findViewById(R.id.dot_ek223);
		dot_ek224 = (View) findViewById(R.id.dot_ek224);
		day_ek175 = (TextView) findViewById(R.id.day_ek175);
		dot_ek225 = (View) findViewById(R.id.dot_ek225);
		dot_ek226 = (View) findViewById(R.id.dot_ek226);
		dot_ek227 = (View) findViewById(R.id.dot_ek227);
		day_ek177 = (TextView) findViewById(R.id.day_ek177);
		dot_ek228 = (View) findViewById(R.id.dot_ek228);
		dot_ek229 = (View) findViewById(R.id.dot_ek229);
		dot_ek230 = (View) findViewById(R.id.dot_ek230);
		day_ek179 = (TextView) findViewById(R.id.day_ek179);
		dot_ek231 = (View) findViewById(R.id.dot_ek231);
		dot_ek232 = (View) findViewById(R.id.dot_ek232);
		dot_ek233 = (View) findViewById(R.id.dot_ek233);
		day_ek181 = (TextView) findViewById(R.id.day_ek181);
		dot_ek234 = (View) findViewById(R.id.dot_ek234);
		dot_ek235 = (View) findViewById(R.id.dot_ek235);
		dot_ek236 = (View) findViewById(R.id.dot_ek236);
		vector_ek11 = (ImageView) findViewById(R.id.vector_ek11);
		label_ek3 = (TextView) findViewById(R.id.label_ek3);
		vector_ek12 = (ImageView) findViewById(R.id.vector_ek12);
		label_ek4 = (TextView) findViewById(R.id.label_ek4);
		vector_ek13 = (ImageView) findViewById(R.id.vector_ek13);
		label_ek5 = (TextView) findViewById(R.id.label_ek5);
		vector_ek14 = (ImageView) findViewById(R.id.vector_ek14);
		label_ek6 = (TextView) findViewById(R.id.label_ek6);
		vector_ek15 = (ImageView) findViewById(R.id.vector_ek15);
		label_ek7 = (TextView) findViewById(R.id.label_ek7);
		vector_ek16 = (ImageView) findViewById(R.id.vector_ek16);
		label_ek8 = (TextView) findViewById(R.id.label_ek8);
		dot_ek237 = (View) findViewById(R.id.dot_ek237);
		dot_ek238 = (View) findViewById(R.id.dot_ek238);
		dot_ek239 = (View) findViewById(R.id.dot_ek239);
		dot_ek240 = (View) findViewById(R.id.dot_ek240);
		dot_ek241 = (View) findViewById(R.id.dot_ek241);
		dot_ek242 = (View) findViewById(R.id.dot_ek242);
		logo_png__1__2 = (ImageView) findViewById(R.id.logo_png__1__2);
		title_ek8 = (TextView) findViewById(R.id.title_ek8);
		ink_ek2 = (View) findViewById(R.id.ink_ek2);
		title_ek9 = (TextView) findViewById(R.id.title_ek9);
		box_shadow_ek2 = (View) findViewById(R.id.box_shadow_ek2);
		_ang_ch_y_ek2 = (TextView) findViewById(R.id._ang_ch_y_ek2);
		_ang_ch__ek2 = (TextView) findViewById(R.id._ang_ch__ek2);
		_____ng_ek2 = (TextView) findViewById(R.id._____ng_ek2);
		_206_ek2 = (TextView) findViewById(R.id._206_ek2);
		_2022_ek2 = (TextView) findViewById(R.id._2022_ek2);
		vector_ek17 = (ImageView) findViewById(R.id.vector_ek17);
		vector_ek18 = (ImageView) findViewById(R.id.vector_ek18);
		th_ng_6_ek2 = (TextView) findViewById(R.id.th_ng_6_ek2);
		vector_ek19 = (ImageView) findViewById(R.id.vector_ek19);
		vector_ek20 = (ImageView) findViewById(R.id.vector_ek20);
		day_ek182 = (TextView) findViewById(R.id.day_ek182);
		day_ek183 = (TextView) findViewById(R.id.day_ek183);
		day_ek184 = (TextView) findViewById(R.id.day_ek184);
		day_ek185 = (TextView) findViewById(R.id.day_ek185);
		day_ek186 = (TextView) findViewById(R.id.day_ek186);
		day_ek187 = (TextView) findViewById(R.id.day_ek187);
		day_ek188 = (TextView) findViewById(R.id.day_ek188);
		day_ek190 = (TextView) findViewById(R.id.day_ek190);
		dot_ek243 = (View) findViewById(R.id.dot_ek243);
		dot_ek244 = (View) findViewById(R.id.dot_ek244);
		dot_ek245 = (View) findViewById(R.id.dot_ek245);
		day_ek192 = (TextView) findViewById(R.id.day_ek192);
		day_ek194 = (TextView) findViewById(R.id.day_ek194);
		dot_ek247 = (View) findViewById(R.id.dot_ek247);
		day_ek196 = (TextView) findViewById(R.id.day_ek196);
		dot_ek248 = (View) findViewById(R.id.dot_ek248);
		day_ek198 = (TextView) findViewById(R.id.day_ek198);
		day_ek200 = (TextView) findViewById(R.id.day_ek200);
		day_ek202 = (TextView) findViewById(R.id.day_ek202);
		dot_ek250 = (View) findViewById(R.id.dot_ek250);
		dot_ek251 = (View) findViewById(R.id.dot_ek251);
		dot_ek252 = (View) findViewById(R.id.dot_ek252);
		day_ek204 = (TextView) findViewById(R.id.day_ek204);
		dot_ek253 = (View) findViewById(R.id.dot_ek253);
		dot_ek254 = (View) findViewById(R.id.dot_ek254);
		dot_ek255 = (View) findViewById(R.id.dot_ek255);
		day_ek206 = (TextView) findViewById(R.id.day_ek206);
		dot_ek256 = (View) findViewById(R.id.dot_ek256);
		dot_ek257 = (View) findViewById(R.id.dot_ek257);
		dot_ek258 = (View) findViewById(R.id.dot_ek258);
		day_ek208 = (TextView) findViewById(R.id.day_ek208);
		dot_ek259 = (View) findViewById(R.id.dot_ek259);
		dot_ek260 = (View) findViewById(R.id.dot_ek260);
		dot_ek261 = (View) findViewById(R.id.dot_ek261);
		day_ek210 = (TextView) findViewById(R.id.day_ek210);
		dot_ek262 = (View) findViewById(R.id.dot_ek262);
		dot_ek263 = (View) findViewById(R.id.dot_ek263);
		dot_ek264 = (View) findViewById(R.id.dot_ek264);
		day_ek212 = (TextView) findViewById(R.id.day_ek212);
		dot_ek265 = (View) findViewById(R.id.dot_ek265);
		dot_ek266 = (View) findViewById(R.id.dot_ek266);
		dot_ek267 = (View) findViewById(R.id.dot_ek267);
		day_ek214 = (TextView) findViewById(R.id.day_ek214);
		dot_ek268 = (View) findViewById(R.id.dot_ek268);
		dot_ek269 = (View) findViewById(R.id.dot_ek269);
		dot_ek270 = (View) findViewById(R.id.dot_ek270);
		day_ek216 = (TextView) findViewById(R.id.day_ek216);
		dot_ek271 = (View) findViewById(R.id.dot_ek271);
		dot_ek272 = (View) findViewById(R.id.dot_ek272);
		dot_ek273 = (View) findViewById(R.id.dot_ek273);
		day_ek218 = (TextView) findViewById(R.id.day_ek218);
		dot_ek274 = (View) findViewById(R.id.dot_ek274);
		dot_ek275 = (View) findViewById(R.id.dot_ek275);
		dot_ek276 = (View) findViewById(R.id.dot_ek276);
		day_ek220 = (TextView) findViewById(R.id.day_ek220);
		dot_ek277 = (View) findViewById(R.id.dot_ek277);
		dot_ek278 = (View) findViewById(R.id.dot_ek278);
		dot_ek279 = (View) findViewById(R.id.dot_ek279);
		day_ek222 = (TextView) findViewById(R.id.day_ek222);
		dot_ek280 = (View) findViewById(R.id.dot_ek280);
		dot_ek281 = (View) findViewById(R.id.dot_ek281);
		dot_ek282 = (View) findViewById(R.id.dot_ek282);
		day_ek224 = (TextView) findViewById(R.id.day_ek224);
		dot_ek283 = (View) findViewById(R.id.dot_ek283);
		dot_ek284 = (View) findViewById(R.id.dot_ek284);
		dot_ek285 = (View) findViewById(R.id.dot_ek285);
		day_ek226 = (TextView) findViewById(R.id.day_ek226);
		dot_ek286 = (View) findViewById(R.id.dot_ek286);
		dot_ek287 = (View) findViewById(R.id.dot_ek287);
		dot_ek288 = (View) findViewById(R.id.dot_ek288);
		day_ek228 = (TextView) findViewById(R.id.day_ek228);
		dot_ek289 = (View) findViewById(R.id.dot_ek289);
		dot_ek290 = (View) findViewById(R.id.dot_ek290);
		dot_ek291 = (View) findViewById(R.id.dot_ek291);
		day_ek230 = (TextView) findViewById(R.id.day_ek230);
		dot_ek292 = (View) findViewById(R.id.dot_ek292);
		dot_ek293 = (View) findViewById(R.id.dot_ek293);
		dot_ek294 = (View) findViewById(R.id.dot_ek294);
		day_ek232 = (TextView) findViewById(R.id.day_ek232);
		dot_ek295 = (View) findViewById(R.id.dot_ek295);
		dot_ek296 = (View) findViewById(R.id.dot_ek296);
		dot_ek297 = (View) findViewById(R.id.dot_ek297);
		day_ek234 = (TextView) findViewById(R.id.day_ek234);
		dot_ek298 = (View) findViewById(R.id.dot_ek298);
		dot_ek299 = (View) findViewById(R.id.dot_ek299);
		dot_ek300 = (View) findViewById(R.id.dot_ek300);
		day_ek236 = (TextView) findViewById(R.id.day_ek236);
		dot_ek301 = (View) findViewById(R.id.dot_ek301);
		dot_ek302 = (View) findViewById(R.id.dot_ek302);
		dot_ek303 = (View) findViewById(R.id.dot_ek303);
		day_ek238 = (TextView) findViewById(R.id.day_ek238);
		dot_ek304 = (View) findViewById(R.id.dot_ek304);
		dot_ek305 = (View) findViewById(R.id.dot_ek305);
		dot_ek306 = (View) findViewById(R.id.dot_ek306);
		day_ek240 = (TextView) findViewById(R.id.day_ek240);
		dot_ek308 = (View) findViewById(R.id.dot_ek308);
		day_ek242 = (TextView) findViewById(R.id.day_ek242);
		dot_ek310 = (View) findViewById(R.id.dot_ek310);
		dot_ek311 = (View) findViewById(R.id.dot_ek311);
		dot_ek312 = (View) findViewById(R.id.dot_ek312);
		day_ek244 = (TextView) findViewById(R.id.day_ek244);
		dot_ek313 = (View) findViewById(R.id.dot_ek313);
		day_ek246 = (TextView) findViewById(R.id.day_ek246);
		dot_ek316 = (View) findViewById(R.id.dot_ek316);
		day_ek248 = (TextView) findViewById(R.id.day_ek248);
		dot_ek319 = (View) findViewById(R.id.dot_ek319);
		dot_ek321 = (View) findViewById(R.id.dot_ek321);
		day_ek250 = (TextView) findViewById(R.id.day_ek250);
		dot_ek323 = (View) findViewById(R.id.dot_ek323);
		day_ek252 = (TextView) findViewById(R.id.day_ek252);
		dot_ek325 = (View) findViewById(R.id.dot_ek325);
		dot_ek326 = (View) findViewById(R.id.dot_ek326);
		dot_ek327 = (View) findViewById(R.id.dot_ek327);
		day_ek254 = (TextView) findViewById(R.id.day_ek254);
		dot_ek328 = (View) findViewById(R.id.dot_ek328);
		dot_ek329 = (View) findViewById(R.id.dot_ek329);
		dot_ek330 = (View) findViewById(R.id.dot_ek330);
		day_ek256 = (TextView) findViewById(R.id.day_ek256);
		dot_ek331 = (View) findViewById(R.id.dot_ek331);
		dot_ek332 = (View) findViewById(R.id.dot_ek332);
		dot_ek333 = (View) findViewById(R.id.dot_ek333);
		day_ek258 = (TextView) findViewById(R.id.day_ek258);
		dot_ek334 = (View) findViewById(R.id.dot_ek334);
		dot_ek335 = (View) findViewById(R.id.dot_ek335);
		dot_ek336 = (View) findViewById(R.id.dot_ek336);
		day_ek260 = (TextView) findViewById(R.id.day_ek260);
		dot_ek337 = (View) findViewById(R.id.dot_ek337);
		dot_ek338 = (View) findViewById(R.id.dot_ek338);
		dot_ek339 = (View) findViewById(R.id.dot_ek339);
		day_ek262 = (TextView) findViewById(R.id.day_ek262);
		dot_ek340 = (View) findViewById(R.id.dot_ek340);
		dot_ek341 = (View) findViewById(R.id.dot_ek341);
		dot_ek342 = (View) findViewById(R.id.dot_ek342);
		day_ek264 = (TextView) findViewById(R.id.day_ek264);
		dot_ek343 = (View) findViewById(R.id.dot_ek343);
		dot_ek344 = (View) findViewById(R.id.dot_ek344);
		dot_ek345 = (View) findViewById(R.id.dot_ek345);
		day_ek266 = (TextView) findViewById(R.id.day_ek266);
		dot_ek346 = (View) findViewById(R.id.dot_ek346);
		dot_ek347 = (View) findViewById(R.id.dot_ek347);
		dot_ek348 = (View) findViewById(R.id.dot_ek348);
		day_ek268 = (TextView) findViewById(R.id.day_ek268);
		dot_ek349 = (View) findViewById(R.id.dot_ek349);
		dot_ek350 = (View) findViewById(R.id.dot_ek350);
		dot_ek351 = (View) findViewById(R.id.dot_ek351);
		day_ek270 = (TextView) findViewById(R.id.day_ek270);
		dot_ek352 = (View) findViewById(R.id.dot_ek352);
		dot_ek353 = (View) findViewById(R.id.dot_ek353);
		dot_ek354 = (View) findViewById(R.id.dot_ek354);
		day_ek272 = (TextView) findViewById(R.id.day_ek272);
		dot_ek355 = (View) findViewById(R.id.dot_ek355);
		dot_ek356 = (View) findViewById(R.id.dot_ek356);
		dot_ek357 = (View) findViewById(R.id.dot_ek357);
		vector_ek21 = (ImageView) findViewById(R.id.vector_ek21);
		label_ek9 = (TextView) findViewById(R.id.label_ek9);
		vector_ek22 = (ImageView) findViewById(R.id.vector_ek22);
		label_ek10 = (TextView) findViewById(R.id.label_ek10);
		vector_ek23 = (ImageView) findViewById(R.id.vector_ek23);
		label_ek11 = (TextView) findViewById(R.id.label_ek11);
		vector_ek24 = (ImageView) findViewById(R.id.vector_ek24);
		active = (TextView) findViewById(R.id.active);
		fill_1 = (ImageView) findViewById(R.id.fill_1);
		group_5 = (ImageView) findViewById(R.id.group_5);
		inactive = (TextView) findViewById(R.id.inactive);
		fill_1_ek1 = (ImageView) findViewById(R.id.fill_1_ek1);
		fill_3 = (ImageView) findViewById(R.id.fill_3);
		fill_5 = (ImageView) findViewById(R.id.fill_5);
		group_9 = (ImageView) findViewById(R.id.group_9);
		inactive_ek1 = (TextView) findViewById(R.id.inactive_ek1);
		vector_ek25 = (ImageView) findViewById(R.id.vector_ek25);
		inactive_ek2 = (TextView) findViewById(R.id.inactive_ek2);
		group_3 = (ImageView) findViewById(R.id.group_3);
		group_6 = (ImageView) findViewById(R.id.group_6);
		inactive_ek3 = (TextView) findViewById(R.id.inactive_ek3);
		calendar_1 = (ImageView) findViewById(R.id.calendar_1);
	
		
		//custom code goes here
	
	}
}
	
	